# Python CircleCI 2.0 configuration file
version: 2  # Used to issue warnings about breaking changes
# Jobs represent single executions of a build defined by a collection of steps.
# If you have only one job, it must be called a build.
jobs:
  # build is the name of your job. You can have multiple jobs, in which case
  # they need to have unique names
  build:
    # The steps of a job occur in an environment called an executor. The
    # common executor in CircleCI is a Docker container. Other options exist,
    # like a macOS environment.
    docker:
      # A Docker image is a file used to create a running Docker container.
      - image: circle/python:3.7
    # Your repo has to be checked out somewhere on the build server. The
    # working directory represents the file path where the repo will be stored.
    working_directory: ~/repo
    # The start of a list of steps to be performed by the build server.
    steps:
      # Step 1: Obtain repo from Github
      - checkout
      # Step 2: Create virtual env and install dependencies
      - run:
          # The CircleCI UI shows every build step taken from the value
          # associated with this name key
          name: install dependencies
          # Commands are run via shell. The | symbol specifies that what follows
          # is a literal set of commands, one per line, exactly as you'd see in
          # a shell script
          command: |
            python3 -m venv venv
            # could also use . venv/bin/activate
            source venv/bin/activate
            pip install -r requirements.txt
      # Step 3: Run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v --cov=calculator
